AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: MikeBarberryDotCom SAM Template

Globals:
  Function:
    Timeout: 15
    MemorySize: 128

Parameters:
  CertificateARN:
    Type: String
  HostedZoneID:
    Type: String
  ImageRepo:
    Type: String
  MongoURI:
    Type: String
  APIKey:
    Type: String
  BuildID:
    Type: String

Resources:
  MikeBarberryDotComAPI:
    Type: AWS::Serverless::Api
    Properties:
      Name: MikeBarberryDotCom
      Description: Log Visits
      StageName: main
      EndpointConfiguration: REGIONAL
      BinaryMediaTypes:
        - '*'
      Domain:
        DomainName: api.mikebarberry.com
        CertificateArn:
          Ref: CertificateARN
        EndpointConfiguration: REGIONAL
        Route53:
          HostedZoneId:
            Ref: HostedZoneID

  MikeBarberryDotComLambda:
    Type: AWS::Serverless::Function
    Metadata:
      DockerTag: nodejs18.x-v1
      DockerContext: .
      Dockerfile: Dockerfile
    Properties:
      FunctionName: MikeBarberryDotCom
      Environment:
        Variables:
          NODE_ENV: production
          MONGO_URI:
            Ref: MongoURI
          API_KEY:
            Ref: APIKey
      PackageType: Image
      Architectures:
        - x86_64
      ImageUri:
        Fn::Sub: ${ImageRepo}:${BuildID}
      Events:
        Root:
          Type: Api
          Properties:
            RestApiId:
              Ref: MikeBarberryDotComAPI
            Path: /
            Method: ANY
        ProxyPlus:
          Type: Api
          Properties:
            RestApiId:
              Ref: MikeBarberryDotComAPI
            Path: /{proxy+}
            Method: ANY

Outputs:
  MikeBarberryDotComLambda:
    Description: 'API root URL'
    Value: 'https://api.mikebarberry.com/'
